format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$conda\
$aws\
$gcloud\
$env_var\
$custom\
$cmd_duration\
$time\
$jobs\
$status\
$line_break\
$character"""

add_newline = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ﬦ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[](bold green) "


[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
ignore_base = false
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[time]
style="bold #ff2a6d"
disabled = false

[username]
style_user = "bold #05d9e8"
show_always=true

[directory]
style = "bold #05d9e8"

[git_status]
format='([$all_status$ahead_behind]($style) )'

