#!/usr/bin/env python3
#
# Promotes the focused window by swapping it with the largest window.

from i3ipc import Connection

def find_biggest_window (container):
    max_leaf = None
    max_area = 0
    for leaf in container.leaves():
        rect = leaf.rect
        area = rect.width * rect.height
        if not leaf.focused and area > max_area:
            max_area = area
            max_leaf = leaf
    return (max_area, max_leaf)

i3 = Connection()

current_window = i3.get_tree().find_focused()
workspace = current_window.workspace()
current_size = current_window.rect.width * current_window.rect.height
(primary_size, primary) = find_biggest_window(workspace)
if primary_size >= current_size:
    i3.command("swap container with con_id %s" % primary.id)
